### ISSUE TITLE
Features, Tech & Suggestions

### ISSUE THREAD

**Issue by HariAcharya80** [rbcrossley/randomNepaliNameGenerator#5]
Hey, I have watched this repo and this is really amazing project. I noticed that we have been using .txt file instead of a api endpoint. I also have some suggestions if we want to move forward.

Firstly, discussion section needs to be enabled in this Repo. So that some folks like me don't open a new discussion thread on issues.

**New Features Ideas :**
1. Add API endpoints for data
2. Add DB for storing the name data
3. Collecting new name suggestions to get new names, adding it to DB
4. Selecting the name in backend,
5. Asking users for the feedback on each name generated to identify the worst performing name and analyzing if the name has some issues like typo or etc. and updating it as required.

**Tech Suggestions**
1. Not compulsory but I would like to recommend: Express.js + MongoDB (Lightweight and efficient) but anything can be used. 

Would like to know what's your view point? @anuzpandey  @rbcrossley

**Comment by anuzpandey** [comment]
@rbcrossley Would you please setup the discussion board for the discussion?

@HariAcharya80 Thank you for the `New Features Ideas`. Let's see what @rbcrossley has his say on this, plus, he has some other ideas as well.

**Comment by HariAcharya80** [comment]
Yeah sure :) I'd love to know @rbcrossley's idea :100: :1st_place_medal:

**Comment by rbcrossley** [comment]
I've set up discussion board. Letting users generate the data is not a good approach in my opinion (without introducing AI like in captcha bot to only verify the answer said by large masses).
